### PR TITLE
Fixes paths parsing to include multiple paths

### PR DESCRIPTION
**Pull request by scalvert**
Fixes incorrectly parsing only a single path when multiple paths are passed.

### CODE REVIEW

**Comment by carakessler** [comment]
Can we add a test for this case?

**Comment by scalvert** [comment]
Yep, working on it, hence the WIP.

**Comment by scalvert** [comment]
I think we do have a test for it, BTW, but just confirming.

**Comment by carakessler** [comment]
If we had a test wouldn't it have been failing previously though?

**Comment by scalvert** [comment]
Let's add a more targeted test when I work on fixing up the expansion code.

**Review by carakessler — APPROVED** [review]

**Pull request merged**
